version: '2'

services:
    db:
        image: postgres
        environment:
          - POSTGRES_DB=myfinance
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres

    spring:
        build:
            context: .
            dockerfile: Dockerfile.api
        volumes:
            - ./:/var/www/symfony
        ports:
            - 8080:8080
        depends_on:
            - db
        environment:
          - POSTGRES_DB=myfinance
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres